version = 1
tools = [
    "codex",
    "pi",
]

[installed_skills.handoff]
added = "2026-05-21"
source = "https://github.com/mattpocock/skills/tree/main/skills/productivity/handoff"
commit_sha = "b6250ed602f8a2b401d49274eb31e15695a0637f"
scope = "project"
