version: "0.0.1"
services:
  minance:
    image: ydeng11/minance:0.0.1-beta
    container_name: minance
    hostname: minance
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:mysql://minance-db:3306/minance?createDatabaseIfNotExist=true
      QUARKUS_DATASOURCE_USERNAME: root
      QUARKUS_DATASOURCE_PASSWORD: minance
      QUARKUS_DATASOURCE__DATASOURCE_NAME__DB_KIND: mysql
    ports:
      - 8911:8080
    networks:
      - minance
    depends_on:
      minance-db:
        condition: service_healthy
    healthcheck:
      test: curl -f http://localhost:8080/q/health/live || exit 1
      start_period: 1s
      interval: 30s
      timeout: 5s
      retries: 5

  console:
    image: nginx:alpine
    container_name: console
    hostname: console
    volumes:
      - ./console-nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./console/:/usr/share/nginx/html/
    ports:
      - 1105:80
    depends_on:
      minance:
        condition: service_healthy
    networks:
      - minance

  metabase:
    #    Docker Image for machines not using arm64 arch
    #    image: metabase/metabase:latest
    #    Use the below two lines only for arm64 machine e.g. mac m1 and m2
    build:
      dockerfile: ./Dockerfile-metabase-arm64
    container_name: metabase
    hostname: metabase
    ports:
      - 11010:3000
    environment:
      MB_DB_TYPE: mysql
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 3306
      MB_DB_USER: root
      MB_DB_PASS: minance
      MB_DB_HOST: minance-db
    healthcheck:
      test: curl -f http://127.0.0.1:3000/api/health || exit 1
      interval: 1m30s
      timeout: 15s
      retries: 5
    depends_on:
      minance-db:
        condition: service_healthy
    networks:
      - minance
  minance-db:
    image: mysql:latest
    container_name: minance-db
    hostname: minance-db
    restart: always
    ports:
      - 6033:3306
    environment:
      MYSQL_ROOT_PASSWORD: minance
    volumes:
      - ./metabase-initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=minance
      start_period: 1s
      interval: 30s
      timeout: 5s
      retries: 5
    networks:
      - minance
networks:
  minance:
    name: minance

volumes:
  mysql-data:
