version: "0.0.1"
services:
  minance:
    image: ydeng11/minance:0.0.2
    container_name: minance
    hostname: minance
    ports:
      - 8911:8888
    healthcheck:
      test: curl -f http://localhost:8888/q/health/live || exit 1
      start_period: 1s
      interval: 30s
      timeout: 5s
      retries: 5

volumes:
  mysql-data:
