version: "3.8"
services:
  minance:
    image: ydeng11/minance:latest
    container_name: minance
    hostname: minance
    ports:
      - "8080:8080"
    volumes:
      - minance-data:/deployments/data
    user: "185"
volumes:
  minance-data:
    driver: local
