/*
 * This file is generated by jOOQ.
 */
package today.ihelio.jooq;


import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import today.ihelio.jooq.tables.Accounts;
import today.ihelio.jooq.tables.FlywaySchemaHistory;


/**
 * A class modelling indexes of tables in minance.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ACCOUNTS_BANK_ID = Internal.createIndex(DSL.name("bank_id"), Accounts.ACCOUNTS, new OrderField[] { Accounts.ACCOUNTS.BANK_ID }, false);
    public static final Index FLYWAY_SCHEMA_HISTORY_FLYWAY_SCHEMA_HISTORY_S_IDX = Internal.createIndex(DSL.name("flyway_schema_history_s_idx"), FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS }, false);
}
