/*
 * This file is generated by jOOQ.
 */
package today.ihelio.jooq;


import today.ihelio.jooq.tables.Accounts;
import today.ihelio.jooq.tables.Banks;
import today.ihelio.jooq.tables.CsvColumnMapping;
import today.ihelio.jooq.tables.FlywaySchemaHistory;
import today.ihelio.jooq.tables.Transactions;


/**
 * Convenience access to all tables in minance.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>minance.accounts</code>.
     */
    public static final Accounts ACCOUNTS = Accounts.ACCOUNTS;

    /**
     * The table <code>minance.banks</code>.
     */
    public static final Banks BANKS = Banks.BANKS;

    /**
     * The table <code>minance.csv_column_mapping</code>.
     */
    public static final CsvColumnMapping CSV_COLUMN_MAPPING = CsvColumnMapping.CSV_COLUMN_MAPPING;

    /**
     * The table <code>minance.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>minance.transactions</code>.
     */
    public static final Transactions TRANSACTIONS = Transactions.TRANSACTIONS;
}
