/*
 * This file is generated by jOOQ.
 */
package today.ihelio.jooq.tables.records;


import java.math.BigDecimal;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import today.ihelio.jooq.tables.Accounts;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AccountsRecord extends UpdatableRecordImpl<AccountsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>accounts.account_id</code>.
     */
    public void setAccountId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>accounts.account_id</code>.
     */
    public Integer getAccountId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>accounts.bank_id</code>.
     */
    public void setBankId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>accounts.bank_id</code>.
     */
    public Integer getBankId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>accounts.bank_name</code>.
     */
    public void setBankName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>accounts.bank_name</code>.
     */
    public String getBankName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>accounts.account_name</code>.
     */
    public void setAccountName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>accounts.account_name</code>.
     */
    public String getAccountName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>accounts.account_type</code>.
     */
    public void setAccountType(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>accounts.account_type</code>.
     */
    public String getAccountType() {
        return (String) get(4);
    }

    /**
     * Setter for <code>accounts.init_balance</code>.
     */
    public void setInitBalance(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>accounts.init_balance</code>.
     */
    public BigDecimal getInitBalance() {
        return (BigDecimal) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AccountsRecord
     */
    public AccountsRecord() {
        super(Accounts.ACCOUNTS);
    }

    /**
     * Create a detached, initialised AccountsRecord
     */
    public AccountsRecord(Integer accountId, Integer bankId, String bankName, String accountName, String accountType, BigDecimal initBalance) {
        super(Accounts.ACCOUNTS);

        setAccountId(accountId);
        setBankId(bankId);
        setBankName(bankName);
        setAccountName(accountName);
        setAccountType(accountType);
        setInitBalance(initBalance);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised AccountsRecord
     */
    public AccountsRecord(today.ihelio.jooq.tables.pojos.Accounts value) {
        super(Accounts.ACCOUNTS);

        if (value != null) {
            setAccountId(value.getAccountId());
            setBankId(value.getBankId());
            setBankName(value.getBankName());
            setAccountName(value.getAccountName());
            setAccountType(value.getAccountType());
            setInitBalance(value.getInitBalance());
            resetChangedOnNotNull();
        }
    }
}
