/*
 * This file is generated by jOOQ.
 */
package today.ihelio.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import today.ihelio.jooq.tables.CsvColumnMapping;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CsvColumnMappingRecord extends UpdatableRecordImpl<CsvColumnMappingRecord> implements Record5<Integer, Integer, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>minance.csv_column_mapping.ccm_id</code>.
     */
    public void setCcmId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>minance.csv_column_mapping.ccm_id</code>.
     */
    public Integer getCcmId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>minance.csv_column_mapping.account_id</code>.
     */
    public void setAccountId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>minance.csv_column_mapping.account_id</code>.
     */
    public Integer getAccountId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>minance.csv_column_mapping.transaction_column</code>.
     */
    public void setTransactionColumn(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>minance.csv_column_mapping.transaction_column</code>.
     */
    public String getTransactionColumn() {
        return (String) get(2);
    }

    /**
     * Setter for <code>minance.csv_column_mapping.input_column</code>.
     */
    public void setInputColumn(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>minance.csv_column_mapping.input_column</code>.
     */
    public String getInputColumn() {
        return (String) get(3);
    }

    /**
     * Setter for <code>minance.csv_column_mapping.date_format</code>.
     */
    public void setDateFormat(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>minance.csv_column_mapping.date_format</code>.
     */
    public String getDateFormat() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, String, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Integer, String, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return CsvColumnMapping.CSV_COLUMN_MAPPING.CCM_ID;
    }

    @Override
    public Field<Integer> field2() {
        return CsvColumnMapping.CSV_COLUMN_MAPPING.ACCOUNT_ID;
    }

    @Override
    public Field<String> field3() {
        return CsvColumnMapping.CSV_COLUMN_MAPPING.TRANSACTION_COLUMN;
    }

    @Override
    public Field<String> field4() {
        return CsvColumnMapping.CSV_COLUMN_MAPPING.INPUT_COLUMN;
    }

    @Override
    public Field<String> field5() {
        return CsvColumnMapping.CSV_COLUMN_MAPPING.DATE_FORMAT;
    }

    @Override
    public Integer component1() {
        return getCcmId();
    }

    @Override
    public Integer component2() {
        return getAccountId();
    }

    @Override
    public String component3() {
        return getTransactionColumn();
    }

    @Override
    public String component4() {
        return getInputColumn();
    }

    @Override
    public String component5() {
        return getDateFormat();
    }

    @Override
    public Integer value1() {
        return getCcmId();
    }

    @Override
    public Integer value2() {
        return getAccountId();
    }

    @Override
    public String value3() {
        return getTransactionColumn();
    }

    @Override
    public String value4() {
        return getInputColumn();
    }

    @Override
    public String value5() {
        return getDateFormat();
    }

    @Override
    public CsvColumnMappingRecord value1(Integer value) {
        setCcmId(value);
        return this;
    }

    @Override
    public CsvColumnMappingRecord value2(Integer value) {
        setAccountId(value);
        return this;
    }

    @Override
    public CsvColumnMappingRecord value3(String value) {
        setTransactionColumn(value);
        return this;
    }

    @Override
    public CsvColumnMappingRecord value4(String value) {
        setInputColumn(value);
        return this;
    }

    @Override
    public CsvColumnMappingRecord value5(String value) {
        setDateFormat(value);
        return this;
    }

    @Override
    public CsvColumnMappingRecord values(Integer value1, Integer value2, String value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CsvColumnMappingRecord
     */
    public CsvColumnMappingRecord() {
        super(CsvColumnMapping.CSV_COLUMN_MAPPING);
    }

    /**
     * Create a detached, initialised CsvColumnMappingRecord
     */
    public CsvColumnMappingRecord(Integer ccmId, Integer accountId, String transactionColumn, String inputColumn, String dateFormat) {
        super(CsvColumnMapping.CSV_COLUMN_MAPPING);

        setCcmId(ccmId);
        setAccountId(accountId);
        setTransactionColumn(transactionColumn);
        setInputColumn(inputColumn);
        setDateFormat(dateFormat);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised CsvColumnMappingRecord
     */
    public CsvColumnMappingRecord(today.ihelio.jooq.tables.pojos.CsvColumnMapping value) {
        super(CsvColumnMapping.CSV_COLUMN_MAPPING);

        if (value != null) {
            setCcmId(value.getCcmId());
            setAccountId(value.getAccountId());
            setTransactionColumn(value.getTransactionColumn());
            setInputColumn(value.getInputColumn());
            setDateFormat(value.getDateFormat());
            resetChangedOnNotNull();
        }
    }
}
