/*
 * This file is generated by jOOQ.
 */
package today.ihelio.jooq.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import today.ihelio.jooq.tables.MinanceCategory;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MinanceCategoryRecord extends UpdatableRecordImpl<MinanceCategoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>minance_category.m_category_id</code>.
     */
    public void setMCategoryId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>minance_category.m_category_id</code>.
     */
    public Integer getMCategoryId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>minance_category.category</code>.
     */
    public void setCategory(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>minance_category.category</code>.
     */
    public String getCategory() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MinanceCategoryRecord
     */
    public MinanceCategoryRecord() {
        super(MinanceCategory.MINANCE_CATEGORY);
    }

    /**
     * Create a detached, initialised MinanceCategoryRecord
     */
    public MinanceCategoryRecord(Integer mCategoryId, String category) {
        super(MinanceCategory.MINANCE_CATEGORY);

        setMCategoryId(mCategoryId);
        setCategory(category);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised MinanceCategoryRecord
     */
    public MinanceCategoryRecord(today.ihelio.jooq.tables.pojos.MinanceCategory value) {
        super(MinanceCategory.MINANCE_CATEGORY);

        if (value != null) {
            setMCategoryId(value.getMCategoryId());
            setCategory(value.getCategory());
            resetChangedOnNotNull();
        }
    }
}
