/*
 * This file is generated by jOOQ.
 */
package today.ihelio.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import today.ihelio.jooq.tables.RawCategoryToMinanceCategory;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RawCategoryToMinanceCategoryRecord extends UpdatableRecordImpl<RawCategoryToMinanceCategoryRecord> implements Record3<Integer, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>minance.raw_category_to_minance_category.rc_to_mc_id</code>.
     */
    public void setRcToMcId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>minance.raw_category_to_minance_category.rc_to_mc_id</code>.
     */
    public Integer getRcToMcId() {
        return (Integer) get(0);
    }

    /**
     * Setter for
     * <code>minance.raw_category_to_minance_category.raw_category</code>.
     */
    public void setRawCategory(String value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>minance.raw_category_to_minance_category.raw_category</code>.
     */
    public String getRawCategory() {
        return (String) get(1);
    }

    /**
     * Setter for
     * <code>minance.raw_category_to_minance_category.minance_category_id</code>.
     */
    public void setMinanceCategoryId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>minance.raw_category_to_minance_category.minance_category_id</code>.
     */
    public Integer getMinanceCategoryId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return RawCategoryToMinanceCategory.RAW_CATEGORY_TO_MINANCE_CATEGORY.RC_TO_MC_ID;
    }

    @Override
    public Field<String> field2() {
        return RawCategoryToMinanceCategory.RAW_CATEGORY_TO_MINANCE_CATEGORY.RAW_CATEGORY;
    }

    @Override
    public Field<Integer> field3() {
        return RawCategoryToMinanceCategory.RAW_CATEGORY_TO_MINANCE_CATEGORY.MINANCE_CATEGORY_ID;
    }

    @Override
    public Integer component1() {
        return getRcToMcId();
    }

    @Override
    public String component2() {
        return getRawCategory();
    }

    @Override
    public Integer component3() {
        return getMinanceCategoryId();
    }

    @Override
    public Integer value1() {
        return getRcToMcId();
    }

    @Override
    public String value2() {
        return getRawCategory();
    }

    @Override
    public Integer value3() {
        return getMinanceCategoryId();
    }

    @Override
    public RawCategoryToMinanceCategoryRecord value1(Integer value) {
        setRcToMcId(value);
        return this;
    }

    @Override
    public RawCategoryToMinanceCategoryRecord value2(String value) {
        setRawCategory(value);
        return this;
    }

    @Override
    public RawCategoryToMinanceCategoryRecord value3(Integer value) {
        setMinanceCategoryId(value);
        return this;
    }

    @Override
    public RawCategoryToMinanceCategoryRecord values(Integer value1, String value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RawCategoryToMinanceCategoryRecord
     */
    public RawCategoryToMinanceCategoryRecord() {
        super(RawCategoryToMinanceCategory.RAW_CATEGORY_TO_MINANCE_CATEGORY);
    }

    /**
     * Create a detached, initialised RawCategoryToMinanceCategoryRecord
     */
    public RawCategoryToMinanceCategoryRecord(Integer rcToMcId, String rawCategory, Integer minanceCategoryId) {
        super(RawCategoryToMinanceCategory.RAW_CATEGORY_TO_MINANCE_CATEGORY);

        setRcToMcId(rcToMcId);
        setRawCategory(rawCategory);
        setMinanceCategoryId(minanceCategoryId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised RawCategoryToMinanceCategoryRecord
     */
    public RawCategoryToMinanceCategoryRecord(today.ihelio.jooq.tables.pojos.RawCategoryToMinanceCategory value) {
        super(RawCategoryToMinanceCategory.RAW_CATEGORY_TO_MINANCE_CATEGORY);

        if (value != null) {
            setRcToMcId(value.getRcToMcId());
            setRawCategory(value.getRawCategory());
            setMinanceCategoryId(value.getMinanceCategoryId());
            resetChangedOnNotNull();
        }
    }
}
