/*
 * This file is generated by jOOQ.
 */
package today.ihelio.jooq.tables.records;


import java.math.BigDecimal;
import java.time.LocalDate;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import today.ihelio.jooq.tables.Transactions;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TransactionsRecord extends UpdatableRecordImpl<TransactionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>transactions.transaction_id</code>.
     */
    public void setTransactionId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>transactions.transaction_id</code>.
     */
    public Integer getTransactionId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>transactions.account_id</code>.
     */
    public void setAccountId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>transactions.account_id</code>.
     */
    public Integer getAccountId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>transactions.category</code>.
     */
    public void setCategory(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>transactions.category</code>.
     */
    public String getCategory() {
        return (String) get(2);
    }

    /**
     * Setter for <code>transactions.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>transactions.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>transactions.transaction_type</code>.
     */
    public void setTransactionType(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>transactions.transaction_type</code>.
     */
    public String getTransactionType() {
        return (String) get(4);
    }

    /**
     * Setter for <code>transactions.transaction_date</code>.
     */
    public void setTransactionDate(LocalDate value) {
        set(5, value);
    }

    /**
     * Getter for <code>transactions.transaction_date</code>.
     */
    public LocalDate getTransactionDate() {
        return (LocalDate) get(5);
    }

    /**
     * Setter for <code>transactions.post_date</code>.
     */
    public void setPostDate(LocalDate value) {
        set(6, value);
    }

    /**
     * Getter for <code>transactions.post_date</code>.
     */
    public LocalDate getPostDate() {
        return (LocalDate) get(6);
    }

    /**
     * Setter for <code>transactions.memo</code>.
     */
    public void setMemo(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>transactions.memo</code>.
     */
    public String getMemo() {
        return (String) get(7);
    }

    /**
     * Setter for <code>transactions.address</code>.
     */
    public void setAddress(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>transactions.address</code>.
     */
    public String getAddress() {
        return (String) get(8);
    }

    /**
     * Setter for <code>transactions.city</code>.
     */
    public void setCity(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>transactions.city</code>.
     */
    public String getCity() {
        return (String) get(9);
    }

    /**
     * Setter for <code>transactions.state_name</code>.
     */
    public void setStateName(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>transactions.state_name</code>.
     */
    public String getStateName() {
        return (String) get(10);
    }

    /**
     * Setter for <code>transactions.country</code>.
     */
    public void setCountry(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>transactions.country</code>.
     */
    public String getCountry() {
        return (String) get(11);
    }

    /**
     * Setter for <code>transactions.zipcode</code>.
     */
    public void setZipcode(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>transactions.zipcode</code>.
     */
    public String getZipcode() {
        return (String) get(12);
    }

    /**
     * Setter for <code>transactions.amount</code>.
     */
    public void setAmount(BigDecimal value) {
        set(13, value);
    }

    /**
     * Getter for <code>transactions.amount</code>.
     */
    public BigDecimal getAmount() {
        return (BigDecimal) get(13);
    }

    /**
     * Setter for <code>transactions.bank_name</code>.
     */
    public void setBankName(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>transactions.bank_name</code>.
     */
    public String getBankName() {
        return (String) get(14);
    }

    /**
     * Setter for <code>transactions.account_name</code>.
     */
    public void setAccountName(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>transactions.account_name</code>.
     */
    public String getAccountName() {
        return (String) get(15);
    }

    /**
     * Setter for <code>transactions.upload_time</code>.
     */
    public void setUploadTime(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>transactions.upload_time</code>.
     */
    public String getUploadTime() {
        return (String) get(16);
    }

    /**
     * Setter for <code>transactions.is_duplicate</code>.
     */
    public void setIsDuplicate(Integer value) {
        set(17, value);
    }

    /**
     * Getter for <code>transactions.is_duplicate</code>.
     */
    public Integer getIsDuplicate() {
        return (Integer) get(17);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TransactionsRecord
     */
    public TransactionsRecord() {
        super(Transactions.TRANSACTIONS);
    }

    /**
     * Create a detached, initialised TransactionsRecord
     */
    public TransactionsRecord(Integer transactionId, Integer accountId, String category, String description, String transactionType, LocalDate transactionDate, LocalDate postDate, String memo, String address, String city, String stateName, String country, String zipcode, BigDecimal amount, String bankName, String accountName, String uploadTime, Integer isDuplicate) {
        super(Transactions.TRANSACTIONS);

        setTransactionId(transactionId);
        setAccountId(accountId);
        setCategory(category);
        setDescription(description);
        setTransactionType(transactionType);
        setTransactionDate(transactionDate);
        setPostDate(postDate);
        setMemo(memo);
        setAddress(address);
        setCity(city);
        setStateName(stateName);
        setCountry(country);
        setZipcode(zipcode);
        setAmount(amount);
        setBankName(bankName);
        setAccountName(accountName);
        setUploadTime(uploadTime);
        setIsDuplicate(isDuplicate);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised TransactionsRecord
     */
    public TransactionsRecord(today.ihelio.jooq.tables.pojos.Transactions value) {
        super(Transactions.TRANSACTIONS);

        if (value != null) {
            setTransactionId(value.getTransactionId());
            setAccountId(value.getAccountId());
            setCategory(value.getCategory());
            setDescription(value.getDescription());
            setTransactionType(value.getTransactionType());
            setTransactionDate(value.getTransactionDate());
            setPostDate(value.getPostDate());
            setMemo(value.getMemo());
            setAddress(value.getAddress());
            setCity(value.getCity());
            setStateName(value.getStateName());
            setCountry(value.getCountry());
            setZipcode(value.getZipcode());
            setAmount(value.getAmount());
            setBankName(value.getBankName());
            setAccountName(value.getAccountName());
            setUploadTime(value.getUploadTime());
            setIsDuplicate(value.getIsDuplicate());
            resetChangedOnNotNull();
        }
    }
}
