/*
 * This file is generated by jOOQ.
 */
package today.ihelio.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CsvColumnMapping implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer ccmId;
    private Integer accountId;
    private String transactionColumn;
    private String inputColumn;
    private String dateFormat;

    public CsvColumnMapping() {}

    public CsvColumnMapping(CsvColumnMapping value) {
        this.ccmId = value.ccmId;
        this.accountId = value.accountId;
        this.transactionColumn = value.transactionColumn;
        this.inputColumn = value.inputColumn;
        this.dateFormat = value.dateFormat;
    }

    public CsvColumnMapping(
        Integer ccmId,
        Integer accountId,
        String transactionColumn,
        String inputColumn,
        String dateFormat
    ) {
        this.ccmId = ccmId;
        this.accountId = accountId;
        this.transactionColumn = transactionColumn;
        this.inputColumn = inputColumn;
        this.dateFormat = dateFormat;
    }

    /**
     * Getter for <code>minance.csv_column_mapping.ccm_id</code>.
     */
    public Integer getCcmId() {
        return this.ccmId;
    }

    /**
     * Setter for <code>minance.csv_column_mapping.ccm_id</code>.
     */
    public void setCcmId(Integer ccmId) {
        this.ccmId = ccmId;
    }

    /**
     * Getter for <code>minance.csv_column_mapping.account_id</code>.
     */
    public Integer getAccountId() {
        return this.accountId;
    }

    /**
     * Setter for <code>minance.csv_column_mapping.account_id</code>.
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * Getter for <code>minance.csv_column_mapping.transaction_column</code>.
     */
    public String getTransactionColumn() {
        return this.transactionColumn;
    }

    /**
     * Setter for <code>minance.csv_column_mapping.transaction_column</code>.
     */
    public void setTransactionColumn(String transactionColumn) {
        this.transactionColumn = transactionColumn;
    }

    /**
     * Getter for <code>minance.csv_column_mapping.input_column</code>.
     */
    public String getInputColumn() {
        return this.inputColumn;
    }

    /**
     * Setter for <code>minance.csv_column_mapping.input_column</code>.
     */
    public void setInputColumn(String inputColumn) {
        this.inputColumn = inputColumn;
    }

    /**
     * Getter for <code>minance.csv_column_mapping.date_format</code>.
     */
    public String getDateFormat() {
        return this.dateFormat;
    }

    /**
     * Setter for <code>minance.csv_column_mapping.date_format</code>.
     */
    public void setDateFormat(String dateFormat) {
        this.dateFormat = dateFormat;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final CsvColumnMapping other = (CsvColumnMapping) obj;
        if (this.ccmId == null) {
            if (other.ccmId != null)
                return false;
        }
        else if (!this.ccmId.equals(other.ccmId))
            return false;
        if (this.accountId == null) {
            if (other.accountId != null)
                return false;
        }
        else if (!this.accountId.equals(other.accountId))
            return false;
        if (this.transactionColumn == null) {
            if (other.transactionColumn != null)
                return false;
        }
        else if (!this.transactionColumn.equals(other.transactionColumn))
            return false;
        if (this.inputColumn == null) {
            if (other.inputColumn != null)
                return false;
        }
        else if (!this.inputColumn.equals(other.inputColumn))
            return false;
        if (this.dateFormat == null) {
            if (other.dateFormat != null)
                return false;
        }
        else if (!this.dateFormat.equals(other.dateFormat))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.ccmId == null) ? 0 : this.ccmId.hashCode());
        result = prime * result + ((this.accountId == null) ? 0 : this.accountId.hashCode());
        result = prime * result + ((this.transactionColumn == null) ? 0 : this.transactionColumn.hashCode());
        result = prime * result + ((this.inputColumn == null) ? 0 : this.inputColumn.hashCode());
        result = prime * result + ((this.dateFormat == null) ? 0 : this.dateFormat.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CsvColumnMapping (");

        sb.append(ccmId);
        sb.append(", ").append(accountId);
        sb.append(", ").append(transactionColumn);
        sb.append(", ").append(inputColumn);
        sb.append(", ").append(dateFormat);

        sb.append(")");
        return sb.toString();
    }
}
