/*
 * This file is generated by jOOQ.
 */
package today.ihelio.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MinanceCategory implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer mCategoryId;
    private String category;

    public MinanceCategory() {}

    public MinanceCategory(MinanceCategory value) {
        this.mCategoryId = value.mCategoryId;
        this.category = value.category;
    }

    public MinanceCategory(
        Integer mCategoryId,
        String category
    ) {
        this.mCategoryId = mCategoryId;
        this.category = category;
    }

    /**
     * Getter for <code>minance_category.m_category_id</code>.
     */
    public Integer getMCategoryId() {
        return this.mCategoryId;
    }

    /**
     * Setter for <code>minance_category.m_category_id</code>.
     */
    public void setMCategoryId(Integer mCategoryId) {
        this.mCategoryId = mCategoryId;
    }

    /**
     * Getter for <code>minance_category.category</code>.
     */
    public String getCategory() {
        return this.category;
    }

    /**
     * Setter for <code>minance_category.category</code>.
     */
    public void setCategory(String category) {
        this.category = category;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final MinanceCategory other = (MinanceCategory) obj;
        if (this.mCategoryId == null) {
            if (other.mCategoryId != null)
                return false;
        }
        else if (!this.mCategoryId.equals(other.mCategoryId))
            return false;
        if (this.category == null) {
            if (other.category != null)
                return false;
        }
        else if (!this.category.equals(other.category))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.mCategoryId == null) ? 0 : this.mCategoryId.hashCode());
        result = prime * result + ((this.category == null) ? 0 : this.category.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MinanceCategory (");

        sb.append(mCategoryId);
        sb.append(", ").append(category);

        sb.append(")");
        return sb.toString();
    }
}
