/*
 * This file is generated by jOOQ.
 */
package today.ihelio.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RawCategoryToMinanceCategory implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer rcToMcId;
    private String rawCategory;
    private Integer minanceCategoryId;

    public RawCategoryToMinanceCategory() {}

    public RawCategoryToMinanceCategory(RawCategoryToMinanceCategory value) {
        this.rcToMcId = value.rcToMcId;
        this.rawCategory = value.rawCategory;
        this.minanceCategoryId = value.minanceCategoryId;
    }

    public RawCategoryToMinanceCategory(
        Integer rcToMcId,
        String rawCategory,
        Integer minanceCategoryId
    ) {
        this.rcToMcId = rcToMcId;
        this.rawCategory = rawCategory;
        this.minanceCategoryId = minanceCategoryId;
    }

    /**
     * Getter for <code>raw_category_to_minance_category.rc_to_mc_id</code>.
     */
    public Integer getRcToMcId() {
        return this.rcToMcId;
    }

    /**
     * Setter for <code>raw_category_to_minance_category.rc_to_mc_id</code>.
     */
    public void setRcToMcId(Integer rcToMcId) {
        this.rcToMcId = rcToMcId;
    }

    /**
     * Getter for <code>raw_category_to_minance_category.raw_category</code>.
     */
    public String getRawCategory() {
        return this.rawCategory;
    }

    /**
     * Setter for <code>raw_category_to_minance_category.raw_category</code>.
     */
    public void setRawCategory(String rawCategory) {
        this.rawCategory = rawCategory;
    }

    /**
     * Getter for
     * <code>raw_category_to_minance_category.minance_category_id</code>.
     */
    public Integer getMinanceCategoryId() {
        return this.minanceCategoryId;
    }

    /**
     * Setter for
     * <code>raw_category_to_minance_category.minance_category_id</code>.
     */
    public void setMinanceCategoryId(Integer minanceCategoryId) {
        this.minanceCategoryId = minanceCategoryId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final RawCategoryToMinanceCategory other = (RawCategoryToMinanceCategory) obj;
        if (this.rcToMcId == null) {
            if (other.rcToMcId != null)
                return false;
        }
        else if (!this.rcToMcId.equals(other.rcToMcId))
            return false;
        if (this.rawCategory == null) {
            if (other.rawCategory != null)
                return false;
        }
        else if (!this.rawCategory.equals(other.rawCategory))
            return false;
        if (this.minanceCategoryId == null) {
            if (other.minanceCategoryId != null)
                return false;
        }
        else if (!this.minanceCategoryId.equals(other.minanceCategoryId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.rcToMcId == null) ? 0 : this.rcToMcId.hashCode());
        result = prime * result + ((this.rawCategory == null) ? 0 : this.rawCategory.hashCode());
        result = prime * result + ((this.minanceCategoryId == null) ? 0 : this.minanceCategoryId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RawCategoryToMinanceCategory (");

        sb.append(rcToMcId);
        sb.append(", ").append(rawCategory);
        sb.append(", ").append(minanceCategoryId);

        sb.append(")");
        return sb.toString();
    }
}
